### ISSUE TITLE
Keys Error

### ISSUE THREAD

**Issue by mounlion** [bencompton/framework7-react#86] opened 2018-01-11 19:05 UTC
<img width="571" alt="2018-01-11 22 05 29" src="https://user-images.githubusercontent.com/17071211/34842113-8e933ac0-f71b-11e7-8997-7460ca7d764c.png">

**Comment by vonubisch** [comment] 2018-01-12 15:37
Unfortunately `framework7-react` does not support `React 16` fully yet. It renders, but a lot of `key` and `ref` errors.
`framework7-react` is compiled from [`framework7-vue`](https://github.com/framework7io/framework7-vue), I think our only hope is when `framework7-vue` is switching to `framework7 v2` that this will be fixed.

See #83 for my plea for `React 16`

**Comment by bencompton** [comment] 2018-04-08 10:47
Closing, since this is a dupe of #83

**Closed by bencompton** 2018-04-08 10:47 UTC
