### ISSUE TITLE
Preloader component not rendering

### ISSUE THREAD

**Issue by valentin93** [bencompton/framework7-react#34] opened 2017-05-03 10:57 UTC
Hi

`<PreloaderF7 color="blue" size="44px"></PreloaderF7>`

Gives an error message
`mapp.entry.js:3738 Uncaught TypeError: _vm._m is not a function`

**Comment by bencompton** [comment] 2017-05-03 12:17
This is a duplicate of this issue: https://github.com/bencompton/framework7-react-app-template/issues/6.

At this point, I still haven't had anyone provide the steps to reproduce this issue. It works in the kitchen sink, and as you can see in this fiddle, it works with your exact props: https://jsfiddle.net/aqzwf4L2/.

Please update the linked issue if you have any additional info on how to reproduce.

**Closed by bencompton** 2017-05-03 12:17 UTC
