### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by vonubisch** [bencompton/framework7-react#83] opened 2017-12-20 11:32 UTC
We are developing a new app in `React` + `Framework7` and using this wonderful package.

When upgrading to `React 16` everything renders ok but brings up a lot of console errors regarding unique `keys` and `refs`. Unfortunately this is something that is not fixable outside the `framework-react` package.

The benefits of `React 16` are huge and the app's performance is vastly improved when using `React 16`.

Unfortunately my `Vue` and `TypeScript` skills are not enough to contribute to this package and there is no way to contribute in any another way.

**Comment by srbala** [comment] 2018-03-10 16:05
I see some work progress in v2 branch,  any tentative timeline for react 16?

**Comment by bencompton** [comment] 2018-04-08 10:50
Closing, since this is a dupe of #69.

**Closed by bencompton** 2018-04-08 10:50 UTC
